/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DevDevlayoutImport } from './routes/dev/_dev_layout'
import { Route as DevDevlayoutIndexImport } from './routes/dev/_dev_layout.index'
import { Route as DevDevlayoutUsersImport } from './routes/dev/_dev_layout.users'
import { Route as DevDevlayoutRecipesImport } from './routes/dev/_dev_layout.recipes'

// Create Virtual Routes

const DevImport = createFileRoute('/dev')()
const AnotherLazyImport = createFileRoute('/another')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DevRoute = DevImport.update({
  path: '/dev',
  getParentRoute: () => rootRoute,
} as any)

const AnotherLazyRoute = AnotherLazyImport.update({
  path: '/another',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/another.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DevDevlayoutRoute = DevDevlayoutImport.update({
  id: '/_dev_layout',
  getParentRoute: () => DevRoute,
} as any)

const DevDevlayoutIndexRoute = DevDevlayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DevDevlayoutRoute,
} as any)

const DevDevlayoutUsersRoute = DevDevlayoutUsersImport.update({
  path: '/users',
  getParentRoute: () => DevDevlayoutRoute,
} as any)

const DevDevlayoutRecipesRoute = DevDevlayoutRecipesImport.update({
  path: '/recipes',
  getParentRoute: () => DevDevlayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/another': {
      id: '/another'
      path: '/another'
      fullPath: '/another'
      preLoaderRoute: typeof AnotherLazyImport
      parentRoute: typeof rootRoute
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevImport
      parentRoute: typeof rootRoute
    }
    '/dev/_dev_layout': {
      id: '/dev/_dev_layout'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevDevlayoutImport
      parentRoute: typeof DevRoute
    }
    '/dev/_dev_layout/recipes': {
      id: '/dev/_dev_layout/recipes'
      path: '/recipes'
      fullPath: '/dev/recipes'
      preLoaderRoute: typeof DevDevlayoutRecipesImport
      parentRoute: typeof DevDevlayoutImport
    }
    '/dev/_dev_layout/users': {
      id: '/dev/_dev_layout/users'
      path: '/users'
      fullPath: '/dev/users'
      preLoaderRoute: typeof DevDevlayoutUsersImport
      parentRoute: typeof DevDevlayoutImport
    }
    '/dev/_dev_layout/': {
      id: '/dev/_dev_layout/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevDevlayoutIndexImport
      parentRoute: typeof DevDevlayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  AnotherLazyRoute,
  DevRoute: DevRoute.addChildren({
    DevDevlayoutRoute: DevDevlayoutRoute.addChildren({
      DevDevlayoutRecipesRoute,
      DevDevlayoutUsersRoute,
      DevDevlayoutIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/another",
        "/dev"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/another": {
      "filePath": "another.lazy.tsx"
    },
    "/dev": {
      "filePath": "dev",
      "children": [
        "/dev/_dev_layout"
      ]
    },
    "/dev/_dev_layout": {
      "filePath": "dev/_dev_layout.tsx",
      "parent": "/dev",
      "children": [
        "/dev/_dev_layout/recipes",
        "/dev/_dev_layout/users",
        "/dev/_dev_layout/"
      ]
    },
    "/dev/_dev_layout/recipes": {
      "filePath": "dev/_dev_layout.recipes.tsx",
      "parent": "/dev/_dev_layout"
    },
    "/dev/_dev_layout/users": {
      "filePath": "dev/_dev_layout.users.tsx",
      "parent": "/dev/_dev_layout"
    },
    "/dev/_dev_layout/": {
      "filePath": "dev/_dev_layout.index.tsx",
      "parent": "/dev/_dev_layout"
    }
  }
}
ROUTE_MANIFEST_END */
